package model306

// Code generated by ../../generators/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/smdx"
	"github.com/andig/gosunspec/typelabel"
)

// Block306 - Reference Point Model - Include to support a standard reference point

const (
	ModelID          = 306
	ModelLabel       = "Reference Point Model"
	ModelDescription = "Include to support a standard reference point"
)

const (
	A   = "A"
	GHI = "GHI"
	Tmp = "Tmp"
	V   = "V"
)

type Block306 struct {
	GHI uint16 `sunspec:"offset=0"`
	A   uint16 `sunspec:"offset=1"`
	V   uint16 `sunspec:"offset=2"`
	Tmp uint16 `sunspec:"offset=3"`
}

func (block *Block306) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "ref_point",
		Length: 4,
		Blocks: []smdx.BlockElement{
			{
				Length: 4,
				Points: []smdx.PointElement{
					{Id: GHI, Offset: 0, Type: typelabel.Uint16, Units: "W/m2", Label: "GHI", Description: "Global Horizontal Irradiance"},
					{Id: A, Offset: 1, Type: typelabel.Uint16, Units: "W/m2", Label: "Amps", Description: "Current measurement at reference point"},
					{Id: V, Offset: 2, Type: typelabel.Uint16, Units: "W/m2", Label: "Voltage", Description: "Voltage  measurement at reference point"},
					{Id: Tmp, Offset: 3, Type: typelabel.Uint16, Units: "W/m2", Label: "Temperature", Description: "Temperature measurement at reference point"},
				},
			},
		}})
}
