package model302

// Code generated by ../../generators/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/smdx"
	"github.com/andig/gosunspec/typelabel"
)

// Block302 - Irradiance Model - Include to support various irradiance measurements

const (
	ModelID          = 302
	ModelLabel       = "Irradiance Model"
	ModelDescription = "Include to support various irradiance measurements"
)

const (
	DFI  = "DFI"
	DNI  = "DNI"
	GHI  = "GHI"
	OTI  = "OTI"
	POAI = "POAI"
)

type Block302Repeat struct {
	GHI  uint16 `sunspec:"offset=0"`
	POAI uint16 `sunspec:"offset=1"`
	DFI  uint16 `sunspec:"offset=2"`
	DNI  uint16 `sunspec:"offset=3"`
	OTI  uint16 `sunspec:"offset=4"`
}

type Block302 struct {
	Repeats []Block302Repeat
}

func (block *Block302) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "irradiance",
		Length: 5,
		Blocks: []smdx.BlockElement{
			{
				Length: 5,
				Type:   "repeating",
				Points: []smdx.PointElement{
					{Id: GHI, Offset: 0, Type: typelabel.Uint16, Units: "W/m2", Label: "GHI", Description: "Global Horizontal Irradiance"},
					{Id: POAI, Offset: 1, Type: typelabel.Uint16, Units: "W/m2", Label: "POAI", Description: "Plane-of-Array Irradiance"},
					{Id: DFI, Offset: 2, Type: typelabel.Uint16, Units: "W/m2", Label: "DFI", Description: "Diffuse Irradiance"},
					{Id: DNI, Offset: 3, Type: typelabel.Uint16, Units: "W/m2", Label: "DNI", Description: "Direct Normal Irradiance"},
					{Id: OTI, Offset: 4, Type: typelabel.Uint16, Units: "W/m2", Label: "OTI", Description: "Other Irradiance"},
				},
			},
		}})
}
