package model305

// Code generated by ../../generators/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/smdx"
	"github.com/andig/gosunspec/typelabel"
)

// Block305 - GPS - Include to support location measurements

const (
	ModelID          = 305
	ModelLabel       = "GPS"
	ModelDescription = "Include to support location measurements"
)

const (
	Alt  = "Alt"
	Date = "Date"
	Lat  = "Lat"
	Loc  = "Loc"
	Long = "Long"
	Tm   = "Tm"
)

type Block305 struct {
	Tm   string `sunspec:"offset=0,len=6"`
	Date string `sunspec:"offset=6,len=4"`
	Loc  string `sunspec:"offset=10,len=20"`
	Lat  int32  `sunspec:"offset=30,sf=-7"`
	Long int32  `sunspec:"offset=32,sf=-7"`
	Alt  int32  `sunspec:"offset=34"`
}

func (block *Block305) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "location",
		Length: 36,
		Blocks: []smdx.BlockElement{
			{
				Length: 36,
				Points: []smdx.PointElement{
					{Id: Tm, Offset: 0, Type: typelabel.String, Units: "hhmmss.sssZ", Length: 6, Label: "Tm", Description: "UTC 24 hour time stamp to millisecond hhmmss.sssZ format"},
					{Id: Date, Offset: 6, Type: typelabel.String, Units: "YYYYMMDD", Length: 4, Label: "Date", Description: "UTC Date string YYYYMMDD format"},
					{Id: Loc, Offset: 10, Type: typelabel.String, Units: "text", Length: 20, Label: "Location", Description: "Location string (40 chars max)"},
					{Id: Lat, Offset: 30, Type: typelabel.Int32, ScaleFactor: "-7", Units: "Degrees", Label: "Lat", Description: "Latitude with seven degrees of precision"},
					{Id: Long, Offset: 32, Type: typelabel.Int32, ScaleFactor: "-7", Units: "Degrees", Label: "Long", Description: "Longitude with seven degrees of precision"},
					{Id: Alt, Offset: 34, Type: typelabel.Int32, Units: "meters", Label: "Altitude", Description: "Altitude measurement in meters"},
				},
			},
		}})
}
