package model806

// Code generated by ../../generators/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/smdx"
	"github.com/andig/gosunspec/typelabel"
)

// Block806 - Flow Battery Model -

const (
	ModelID          = 806
	ModelLabel       = "Flow Battery Model"
	ModelDescription = ""
)

const (
	BatStTBD = "BatStTBD"
	BatTBD   = "BatTBD"
)

type Block806Repeat struct {
	BatStTBD uint16 `sunspec:"offset=0"`
}

type Block806 struct {
	BatTBD uint16 `sunspec:"offset=0"`

	Repeats []Block806Repeat
}

func (block *Block806) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "flow_battery",
		Length: 2,
		Blocks: []smdx.BlockElement{
			{
				Length: 1,
				Points: []smdx.PointElement{
					{Id: BatTBD, Offset: 0, Type: typelabel.Uint16, Mandatory: true, Label: "Battery Points To Be Determined", Description: ""},
				},
			},
			{Name: "battery_string",
				Length: 1,
				Type:   "repeating",
				Points: []smdx.PointElement{
					{Id: BatStTBD, Offset: 0, Type: typelabel.Uint16, Mandatory: true, Label: "Battery String Points To Be Determined", Description: ""},
				},
			},
		}})
}
